### ISSUE TITLE
Container doesn’t open on map

### ISSUE THREAD

**Issue by powerkor** [kamcknig/pick-up-stix#122]
When placing a container on the map, it doesn’t open anymore. Running icrpg not 5e

**Comment by kamcknig** [comment]
Hi, @powerkor , can you check this issue and my response there? https://github.com/kamcknig/pick-up-stix/issues/114 This might be the same issue. There is currently a bug that when updating the token from the config sheet, it actually shows the open image rather than the closed image. I'll have a fix for that today if so

**Comment by kamcknig** [comment]
Should be fixed in release 0.11.7. You might need to manually update as there were issues for awhile with automatic updates of my module
