### ISSUE TITLE
Container still not functional

### ISSUE THREAD

**Issue by powerkor** [kamcknig/pick-up-stix#124]
**Describe the bug*
Dragging item onto screen and selecting container doesn’t put that item in the container

**To Reproduce**
Click and drag item to screen and select container
Opening the container has nothing in it until you drag the item into the container again

**Foundry Version**
Stable 6.6

**Pick-Up-Stix Version**
Latest 0.11.7

**Comment by kamcknig** [comment]
@powerkor Hi, this is actually intended. Using an item to create a container simply makes the container. This is because it was the only way I had to create a container at first. After that I added the ability to create containers using the 'create item' button in the items directory and you could then edit that container in the directory to add any starting items. 

However, I think that's a decent idea, and I'll add an item to my backlog to at least add a game setting so that you can choose to auto add an item like that or not.

**Comment by kamcknig** [comment]
Added to my trello board
