### ISSUE TITLE
Dialog claims data migration required without saying which module is demanding it or why

### ISSUE THREAD

**Issue by Arkanmann** [kamcknig/pick-up-stix#130]
I'm running Foundry 0.6.6 on a Mac. The dialog box only appears when I have pick-up-stix enabled, either on launch, or after reload upon activating it via manage modules. At minimum, the dialog box should indicate who is asking for this. But I'm not even sure I understand what data needs migrating from/to where. More information is required. 

![image](https://user-images.githubusercontent.com/66251565/95341879-c6444400-0884-11eb-9e17-8de0f907b54c.png)

**Comment by kamcknig** [comment]
@Arkanmann Hi, thank you! You are right and I have this to fix in my backlog. I believe there is a logic error that if you've never used it in a world it will show that as well when it shouldn't but in that case it will be harmless. I definitely need to add the module name to the title, complete oversight. Thank you!

Right now the migraiton actually only matters when moving from a release below 0.11.x to one in the 0.11.x > range. Otherwise it's benign even if it does show up
