### ISSUE TITLE
Sounds and resize not working

### ISSUE THREAD

**Issue by Bryn1701** [kamcknig/pick-up-stix#134]
First of all, thank you for a great mod! This is very cleaver of you. 
There is an issue when I try to set sounds for opening and closing a container, that no matter which directory the sound is in, I cannot seem to hear it, neither can my players. 

The second issue is that items dropped on the map, cannot be resized like containers.

**Comment by kamcknig** [comment]
@Bryn1701 Thanks! Much appreciated!

I'll take a look at the sounds to see if that's an issue there. 

The second issue is a known issue. Previously I was using the same sheet to configure both a container and an item, but that meant that you couldn't really edit a lot of the item's other fields. In a recent update I made it so that you could use the normal Item config sheet to edit the item so you had access to all of the normal data. However, scale isn't normally available for items. I have it on my backlog to be able to do that but I need to find a way to consistely edit the size of both container tokens and normal item tokens.

**Comment by kamcknig** [comment]
Hi, @Bryn1701, I have retested the sounds and they seem to be working fine for me. If you could open a new item if it is still an issue in the latest version of my module that'd be great. please make sure to include version details for foundry, system and module.
