### ISSUE TITLE
wrong behavior whit "personal chest"

### ISSUE THREAD

**Issue by capoeria** [kamcknig/pick-up-stix#172]
Each PC has a personal chest located in his room at the inn.
Other characters cannot access it (through permissions) and the owner can remove things from the chest without problems, but when he deposits them from his inventory, they are not subtracted.

**Comment by kamcknig** [comment]
Hi, thanks for the report! This is a known issue and should hopefully be fixed in the next version.

**Comment by kamcknig** [comment]
I believe, if you drop the item onto the token itself it will work. I believe you only see this behavior if you drop the item onto the container sheet. Might be a workaround

**Comment by capoeria** [comment]
I have tried that, but with no results

https://www.loom.com/share/396c3d936a61415484e10012fcfe9edf

**Comment by capoeria** [comment]
Sorry, You are right. I had "toggle edit" enabled. With your method I can do that. Thank you

**Comment by kamcknig** [comment]
@capoeria , There might be weirdness because I'm not sure how permissions will act if you change them. Can you provide exact steps that repro the problem? I have to set permissions on the items created so that players can actually interact with them, but a lot of the functions such as adding items, deleting them, and such all get forwarded to a GM player (it's not happening on the client  machine that necessarily requested the action) so even if you set up permissions, they might not work how you think (and since I haven't tested changing permissions after item creations i'm not sure either)

**Comment by capoeria** [comment]
With this recent version I cant access to the sheet

**Comment by kamcknig** [comment]
You'll have to give me more details. Steps you used. Versions of foundry and system. Make sure to turn off all other modules. This 100% worked for me in the newest version.

**Comment by capoeria** [comment]
https://www.loom.com/share/f5fbb6c1eb5e437c9d6b81d093880edd

**Comment by kamcknig** [comment]
@capoeria It would appear, that you have only one player logged in and that player is not a GM user. There must be at least one GM user logged in.

**Comment by capoeria** [comment]
I am connected as GM

**Comment by kamcknig** [comment]
You should now be able to open chests in 0.13.8

**Comment by capoeria** [comment]
Thank you, I can open them now. I will look forward subsequent versions to introduce the "personal chest"
Thnak you again

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
