### ISSUE TITLE
Items can keep getting respawned

### ISSUE THREAD

**Issue by VoltCruelerz** [kamcknig/pick-up-stix#38]
While toying around with the script and attempting to figure out how chests work, I picked up and dropped several items.  I then deleted these items, but upon reloading the map, they returned.  I cannot seem to delete them by any means.  They simply come back when I reload the page.

**Comment by VoltCruelerz** [comment]
After further investigation, to actually destroy the items, deleting the tokens doesn't seem to work.  Instead, you have to have a PC pick them up and then delete them from their inventory

**Comment by kamcknig** [comment]
Hi! Could you please provide exact reproduction steps and include the version of Foundry and the module? Thanks!

**Comment by VoltCruelerz** [comment]
After some digging, here's two ways, which result in slightly different results.

1. Place a chest on the map.  Do NOT change any settings.
2. Pick it up as a PC.
3. Drag the item back onto the map.
4. Add an item to the chest through the right click menu, but do NOT make it a container.
5. Pick up the container (and its contents)
6. Drag both back onto the map.
7. Delete both.
8. Reload page (ie via Settings -> Manage Modules -> Save Module Settings)
9. Observe the chest and the item are both back.

1. Place a chest on the map.  Do NOT change any settings.
2. Pick it up as a PC.
3. Drag the item back onto the map.
4. Open the chest's right click menu, make it a container, and add an item inside it.
5. Pick up the container (and its contents)
6. Drag both back onto the map.
7. Delete the original chest, the new chest, and the item.
8. Reload page (ie via Settings -> Manage Modules -> Save Module Settings)
9. Observe the chest and the item are both back.

**Comment by kamcknig** [comment]
I'm having trouble reproducing this one. 

I've just released v0.4.2 which fixes a permission issue and an image sizing issue in the item selection window.

For step 3 you say "pick up the chest", but if the item is a container, then it cannot be picked up so could you clarify there?

For step 4 is it the GM dragging back onto the map from the player after they pick it up? There was a permission issue with a PC dropping onto the map that I just fixed so I'd like to clarify if it was the GM or not. If it was not and you were still able to drop it, then it could be fixed with this permission issue. 

Could you possibly make a video of your steps? I use https://icecreamapps.com/Screen-Recorder/ for videos, or the built-in windows recording.

**Comment by VoltCruelerz** [comment]
3: If I as the GM have a PC token selected and click on an adjacent container, the PC's inventory gets the container added to it, but the item also remains on the map.  In this case, the character sheet has the chest under loot.
4: GM dragging

https://www.youtube.com/watch?v=IVAPMM2ozYQ&feature=youtu.be

**Comment by kamcknig** [comment]
3. Oh I see, OK. That's a "misunderstanding" as to how it works. So when you add an item to the map it automatically "adds itself" as an item to be picked up. And when you turn it into a container it's still there. If you open that container menu, then you'll see that the item itself is marked as a "1" count by default and you'll have to change that to 0 to not get the container (though it's simply an item in the inventory not actually a container). I actually think I'll remove that so that it starts completely empty. Not very intuitive the way it is now, but it was an oversight that I just never fixed/changed.

OK, the video is super interesting. I'll try it again later today but I'm definitely not getting that behavior. If you could possibly send the console logs as well that might be helpful so I can compare them to the logs I get. (all the way through the refresh would be great). And then of course let me know if it's still doing it in the 0.4.2 update if you get a chance.

**Comment by kamcknig** [comment]
Have you tried it without any other modules installed as well? Another use has reported issues with Forien's Quest Log, Token Animation Tools and Token Hotbar, though his problems with those were that he could not drop items onto the map rather than this specific issue.
