### ISSUE TITLE
Suggestion: Container Usability

### ISSUE THREAD

**Issue by VoltCruelerz** [kamcknig/pick-up-stix#41]
- Item Returns: allow users to return items to a chest (currently, dragging an item onto a chest just places it atop it on the map)
- Item Window: when opening a chest, create a popup window that displays its contents with a button to move an item to your inventory
- Stealthy Retrieval: rogues do love picking up items in chests without telling the party.  the messages seem to be public, so it would be nice if they were whispered to player and GM.
- Search: as I add more items, it becomes clear that a search feature would be very useful

**Comment by kamcknig** [comment]
Item returns: This is actually a suggestion someone else made on discord that I thought was a great idea and will be implementing.

Item Window: I thought about rolling my own for this and probably still will at some point. I have just released version 0.4.0 that integrates with the lootsheet5enpc module so that you can use an actor token and set that token up as a chest which will open the loot sheet from that module

Stealth: I've also got this in my backlog, to be able to loot dead bodies, possibly even attempt to steal from living bodies with notifications to the GM if it fails or something.

Great suggestions!

**Comment by kamcknig** [comment]
I've added these to the future considerations section of the README, so I'll close this item. Thank you!
